-- Create a table for storing blog posts
create table public.blogs (
  id bigint generated by default as identity primary key,
  title text not null,
  link text not null,
  description text,
  source_url text,
  topic_tags text[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.blogs enable row level security;

-- Create policies (modify as needed for your app's security model)
-- Allow read access to everyone
create policy "Enable read access for all users" on public.blogs
  for select using (true);

-- Allow insert access to authenticated users (or service role)
create policy "Enable insert for authenticated users only" on public.blogs
  for insert with check (auth.role() = 'authenticated' OR auth.role() = 'service_role');
