-- Create a table for storing blog posts
create table public.blogs (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  link text, -- legacy field, can be same as slug
  content text,
  description text, -- short summary
  image_url text,
  is_published boolean default false,
  
  -- SEO Fields
  meta_title text,
  meta_description text,
  canonical_url text,
  topic_tags text[],
  
  -- Structured Data
  faq_data jsonb default '[]'::jsonb,
  schema_data jsonb default '{}'::jsonb,
  
  -- Configuration
  template_id text default 'standard',
  source_url text, -- for reference if scraped/generated
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.blogs enable row level security;

-- Create policies
-- Allow read access to everyone
create policy "Enable read access for all users" on public.blogs
  for select using (true);

-- Allow all access to authenticated users
create policy "Enable all access for authenticated users" on public.blogs
  for all using (auth.role() = 'authenticated');

-- Create a storage bucket for blog images if it doesn't exist (handled via dashboard usually, but here for ref)
-- insert into storage.buckets (id, name) values ('sadia', 'sadia');
-- create policy "Public Access" on storage.objects for select using ( bucket_id = 'sadia' );
-- create policy "Auth Upload" on storage.objects for insert with check ( bucket_id = 'sadia' and auth.role() = 'authenticated' );
